### ISSUE TITLE
Include aliases in repo

### ISSUE THREAD

**Issue by glensc** [giberti/commonmark-emoji-extension#2]
From https://github.com/giberti/commonmark-emoji-extension/tree/v0.3#providing-aliases:

> 
> ### Providing Aliases
> 
> GitHub and Slack both shortcuts that do not map directly to the official Unicode CLDR Short Name. Mappings can be injected at the time the instance of `EmojiExtension` is created.
> 
> The Aliases should be passed as an associative array with the key being the new alias and the value being the CLDR Short Name equivalent.
> 
> ```php
> $aliases = [
>     ':coffee:' => ':hot_beverage:',
>     ':smile:' => ':grinning_face_with_smiling_eyes:',
>     // ... any other aliases you wish to support
> ];

Perhaps provide the list in this project itself to prevent duplication of multiple parties?

**Comment by giberti** [comment]
I did consider that, but I believe it goes beyond the purpose of this package. The primary concern is how to handle internationalization.  It's a veritable pandora's box. The names used in the [emoji-data](https://github.com/giberti/emoji-data) package can be handled by internationalization already because they're simply a constant safe variant of the official Unicode names.

For example, `:coffee:` vs. `:caffè:` vs. `: kaffi:` vs. `: kofe:` vs. `: café:`

**Comment by glensc** [comment]
I had in mind that maintaining the lists for GitHub and Slack aliases is community maintained. Maybe they already have, I have not searched.
